### ISSUE TITLE
Try to replace Teambox with OpenAtrium2.0

### ISSUE THREAD

**Issue by dashohoxha** [Labdoo/Labdoo#3]
- First watch this tutorial: http://vimeo.com/70196365

 - Then try it on Pantheon: https://dashboard.getpantheon.com/products/openatrium2/spinup

 - Or try it on a local installation.

 - Try to implement the current projects and groups (that exist on teambox) using the features of OpenAtrium2.0

Note: Other people responsible for this task, besides @dashohoxha, are @jmasukaw and @greggmarshall .

**Comment by dashohoxha** [comment]
I am not sure whether the idea of using OA is still relevant.
For the time being I am closing this issue as irrelevant, and later we can create another issue if we think we should give it another try.

**Comment by jrosgiralt** [comment]
Right, I spent some time trying OA, in the end my conclusion was that it was too heavy loaded providing a large feature set that we don't necessarily need, with a large number of extra modules that would have added complexity and made the site less responsive (requiring more HW resources) and the code more difficult to maintain/scale in the long run. Instead of using OA, the approach i took was to use "organic groups" and develop our own "teams framework":  https://www.labdoo.org/teams
