### ISSUE TITLE
Reorganize menus at labdoo.org

### ISSUE THREAD

**Issue by dashohoxha** [Labdoo/Labdoo#81]
It seems to me that the top menus at labdoo.org can be reorganized a bit to be more compact. For example all the `My . . .` items can be grouped together, etc.
However this is just an opinion.

**Comment by jrosgiralt** [comment]
They are presented in this way because a central element to the design is that there are four core objects around which the architecture and user experience evolves: doojects, dootrips, edoovillages and hubs.  It is important that at any page, these objects are accessible. The other approach like you say, would have been to prioritize "my objects" vs "all objects", but that would demote the four central objects to a second level.
