### ISSUE TITLE
Tagging is buggy / tagged devices not shown

### ISSUE THREAD

**Issue by der-eismann** [Labdoo/Labdoo#89]
Hey everyone,

did you just change something on the website? I can't tag any devices. I tried it twice now but the tagged devices don't show up under "My dootronics". 
However I received a confirmation e-mail for the two dootronics with the same information:
https://www.labdoo.org/de/content/000008705
and
https://www.labdoo.org/de/content/000008706

Could you fix this bug? Or do you need any more information?

**Comment by labdoo-org** [comment]
Hi Philipp,

There was no change on the system. The tagging works fine, the issue
however is that the email you got had the wrong link. This happens only
under the rare occasion when someone deletes a laptop. The tagging system
is designed so that even if someone deletes a laptops, the next time a new
laptop is tagged, it will take the deleted laptop ID. This is to ensure
that the sequence of laptops tagged never has gaps.

The bug however occurs when generating the email, because it sends the
wrong link. But if you check your tagged laptops, you will see that they
got the correct ID (for instance: https://www.labdoo.org/content/000008678).

We only learned about this issue of the email sending the wrong link a few
days ago, because deletion of laptops is a very rare event. This was
reported here:
https://www.labdoo.org/content/assigned-and-mailed-id-are-different

I will soon fix it so that the sent email provides the correct link.

On your other question about the laptops not showing up in your dashboard,
that's because we only refresh dashboards once every hour. That's done to
avoid overwhelming the servers with lots of calculations. This is explained
here: https://www.labdoo.org/content/visualization-dashboards (at the end
of this page).

If you check your dashboard, you will see that now all your laptops show up
as expected: https://www.labdoo.org/content/dootronics-dashboard?u=1457

BTW, we don't use github to report tickets, we use instead 'tasks' from the
Labdoo software development team, because most of users don't have github
accounts and this way we keep all feedback/bug reports confined in one
place: https://www.labdoo.org/content/software-development/activities

Thanks.

**Comment by jrosgiralt** [comment]
The issue about the email reporting the wrong email is now resolved:
https://github.com/Labdoo/Labdoo/commit/f5db2cd2f11dee23264864c282f9b86e1814b32a
